# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Cursinho Livre Caburé"
description:	       "Cursinho pré-vestibular popular e totalmente gratuito em Araraquara/SP"
tagline:               "Cursinho Livre Caburé - Araraquara/SP"
author:              "Cursinho Livre Caburé"
url: "http://www.cursinhocabure.org/"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
