# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Sobre', folder: 'pages', file: 'about.html'}
- {name: 'Como funciona', folder: 'pages', file: 'construindo.html'}
- {name: 'Processo seletivo', folder: 'pages', file: 'processoseletivo.html'}
- {name: 'Notícias', folder: 'pages', file: 'construindo.html'}
- {name: 'Apoie', folder: 'pages', file: 'construindo.html'}
- {name: 'Equipe', folder: 'pages', file: 'construindo.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook', link: 'https://www.facebook.com/cursinhocabure/'}
- {icon: 'instagram', link: 'https://instagram.com/'}
- {icon: 'envelope', link: 'mailto:cursinhocabure@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text

post_date_prefix: 'Publicado em'
